# -*- coding: utf-8 -*-
"""RL3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiBMqu-kH0b6xtXzuEu9HLpV3qbAfkUk
"""

# ============================================================
# TD3 EV CHARGING OPTIMIZATION
# COMMIT 1 — ENVIRONMENT IMPLEMENTATION
# ============================================================

import numpy as np
import pandas as pd
import gymnasium as gym
from gymnasium import spaces



# 1. LOAD DATASET


DATA_PATH = (
    "/kaggle/input/datasets/ziya07/"
    "electric-vehicle-charging-demand-dataset/"
    "ev_charging_dataset.csv"
)

print("Loading EV charging dataset...")

df = pd.read_csv(DATA_PATH)

print(f"Dataset loaded: {df.shape}")



# 2. PREPARE TEMPORAL PROFILE


df["timestamp"] = pd.to_datetime(df["timestamp"])

df = df.sort_values("timestamp").reset_index(drop=True)

# Extract hour and date
df["hour"] = df["timestamp"].dt.hour
df["date"] = df["timestamp"].dt.date

# Keep the variables required by the RL environment
profile = df[
    [
        "timestamp",
        "electricity_price",
        "station_load",
        "renewable_energy_ratio",
        "charging_demand",
        "hour",
        "date",
    ]
].copy()

print(f"Profile prepared: {profile.shape}")



# 3. NORMALIZATION FUNCTION


def normalize(value, column):
    """
    Min-max normalization using the observed dataset range.

    Returns a value approximately within [0, 1].
    """

    column_min = df[column].min()
    column_max = df[column].max()

    if column_max == column_min:
        return 0.0

    normalized = (value - column_min) / (column_max - column_min)

    return float(np.clip(normalized, 0.0, 1.0))



# 4. EV CHARGING ENVIRONMENT


class EVChargingEnv(gym.Env):

    """
    EV Charging Optimization Environment

    Action:
        Continuous charging intensity from 0 to 1.

        0.0 = no additional charging
        1.0 = maximum charging

    Observation:
        8 normalized variables:

        0. electricity price
        1. station load
        2. renewable energy ratio
        3. charging demand
        4. hour
        5. queue length proxy
        6. waiting time proxy
        7. charging demand proxy
    """

    metadata = {"render_modes": []}

    def __init__(self, profile, max_steps=96):

        super().__init__()

        self.profile = profile.reset_index(drop=True)

        self.max_steps = max_steps

        self.current_step = 0
        self.start_index = 0

        # ----------------------------------------------------
        # Continuous action:
        # 0 = no charging
        # 1 = maximum charging
        # ----------------------------------------------------

        self.action_space = spaces.Box(
            low=np.array([0.0], dtype=np.float32),
            high=np.array([1.0], dtype=np.float32),
            dtype=np.float32,
        )

        # ----------------------------------------------------
        # Observation:
        # 8 normalized features
        # ----------------------------------------------------

        self.observation_space = spaces.Box(
            low=0.0,
            high=1.0,
            shape=(8,),
            dtype=np.float32,
        )


      ### # RESET


    def reset(self, seed=None, options=None):

        super().reset(seed=seed)

        # Make sure there is enough data for an episode
        max_start = len(self.profile) - self.max_steps

        if max_start <= 0:
            self.start_index = 0
        else:
            self.start_index = self.np_random.integers(
                0,
                max_start
            )

        self.current_step = 0

        observation = self._get_observation()

        info = {
            "start_index": self.start_index,
            "timestamp": self.profile.iloc[
                self.start_index
            ]["timestamp"],
        }

        return observation, info


    #### OBSERVATION


    def _get_observation(self):

        index = self.start_index + self.current_step

        index = min(index, len(self.profile) - 1)

        row = self.profile.iloc[index]

        # ----------------------------------------------------
        # Normalize environmental variables
        # ----------------------------------------------------

        price = normalize(
            row["electricity_price"],
            "electricity_price"
        )

        load = normalize(
            row["station_load"],
            "station_load"
        )

        renewable = normalize(
            row["renewable_energy_ratio"],
            "renewable_energy_ratio"
        )

        demand = normalize(
            row["charging_demand"],
            "charging_demand"
        )

        # ----------------------------------------------------
        # Normalize hour
        # ----------------------------------------------------

        hour = float(row["hour"]) / 23.0

        # ----------------------------------------------------
        # Queue and waiting proxies
        #
        # The current dataset profile does not contain
        # queue_length/waiting_time, so we use normalized
        # demand/load proxies for the initial environment.
        # ----------------------------------------------------

        queue_proxy = load

        waiting_proxy = demand

        # Additional demand/load representations
        load_proxy = load

        demand_proxy = demand

        observation = np.array(
            [
                price,
                load,
                renewable,
                demand,
                hour,
                queue_proxy,
                waiting_proxy,
                load_proxy,
            ],
            dtype=np.float32,
        )

        return np.clip(
            observation,
            0.0,
            1.0
        )


    #### STEP


    def step(self, action):

        # Ensure action is a valid scalar
        action = np.asarray(action, dtype=np.float32)

        action_value = float(
            np.clip(action[0], 0.0, 1.0)
        )

        index = self.start_index + self.current_step

        index = min(index, len(self.profile) - 1)

        row = self.profile.iloc[index]

        # ----------------------------------------------------
        # Current normalized state variables
        # ----------------------------------------------------

        load = normalize(
            row["station_load"],
            "station_load"
        )

        demand = normalize(
            row["charging_demand"],
            "charging_demand"
        )

        price = normalize(
            row["electricity_price"],
            "electricity_price"
        )

        renewable = normalize(
            row["renewable_energy_ratio"],
            "renewable_energy_ratio"
        )

        # ----------------------------------------------------
        # Reward components
        # ----------------------------------------------------

        # Penalty for increasing station load
        load_penalty = action_value * load

        # Penalty when charging demand is high
        demand_penalty = action_value * demand

        # Waiting penalty decreases as charging action increases
        waiting_penalty = (1.0 - action_value) * 0.25

        # Penalty for charging when electricity price is high
        price_penalty = action_value * price

        # Reward for using renewable energy
        renewable_bonus = action_value * renewable

        # ----------------------------------------------------
        # Total reward
        # ----------------------------------------------------

        reward = (
            -0.5 * load_penalty
            -0.5 * demand_penalty
            -0.4 * waiting_penalty
            -0.3 * price_penalty
            +0.5 * renewable_bonus
        )

        reward = float(reward)

        # ----------------------------------------------------
        # Move environment forward
        # ----------------------------------------------------

        self.current_step += 1

        terminated = False

        truncated = self.current_step >= self.max_steps

        observation = self._get_observation()

        info = {
            "action": action_value,
            "reward_components": {
                "load_penalty": float(load_penalty),
                "demand_penalty": float(demand_penalty),
                "waiting_penalty": float(waiting_penalty),
                "price_penalty": float(price_penalty),
                "renewable_bonus": float(renewable_bonus),
            },
        }

        return (
            observation,
            reward,
            terminated,
            truncated,
            info,
        )



### 5. CREATE ENVIRONMENT INSTANCE


env = EVChargingEnv(
    profile=profile,
    max_steps=96
)

print()
print("=" * 70)
print("ENVIRONMENT SANITY TEST")
print("=" * 70)

print("\nAction space:")
print(env.action_space)

print("\nObservation space:")
print(env.observation_space)



# 6. RESET TEST


obs, info = env.reset(seed=42)

print("\nInitial observation:")
print(obs)

print("\nInitial information:")
print(info)



### 7. STEP TEST


action = np.array(
    [0.5],
    dtype=np.float32
)

next_obs, reward, terminated, truncated, info = env.step(
    action
)

print("\nAfter one step:")
print("Action:", action)
print("Reward:", reward)
print("Next observation:", next_obs)
print("Terminated:", terminated)
print("Truncated:", truncated)
print("Info:", info)



#### 8. VALIDATION


assert isinstance(env, EVChargingEnv)

assert env.action_space.shape == (1,)

assert env.observation_space.shape == (8,)

assert np.all(obs >= 0.0)
assert np.all(obs <= 1.0)

assert np.all(next_obs >= 0.0)
assert np.all(next_obs <= 1.0)

assert np.isfinite(reward)

assert not terminated

print("\nSanity test passed.")
print("=" * 70)

