# -*- coding: utf-8 -*-
"""EV-ch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiBMqu-kH0b6xtXzuEu9HLpV3qbAfkUk
"""

# ============================================================
# REWARD & POLICY VALIDATION
# ============================================================

import numpy as np

print("=" * 70)
print("COMMIT 2 — EV CHARGING ENVIRONMENT VALIDATION")
print("=" * 70)


def evaluate_fixed_policy(env, action_value, n_episodes=5):
    """
    Evaluate the environment using a fixed charging action.
    """

    episode_rewards = []
    episode_lengths = []

    for episode in range(n_episodes):

        obs, info = env.reset(seed=100 + episode)

        total_reward = 0.0
        steps = 0

        while True:

            action = np.array(
                [action_value],
                dtype=np.float32
            )

            obs, reward, terminated, truncated, info = env.step(
                action
            )

            total_reward += float(reward)
            steps += 1

            if terminated or truncated:
                break

        episode_rewards.append(total_reward)
        episode_lengths.append(steps)

    return {
        "mean_reward": float(np.mean(episode_rewards)),
        "std_reward": float(np.std(episode_rewards)),
        "mean_length": float(np.mean(episode_lengths)),
        "episode_rewards": episode_rewards
    }



# ============================================================
# RANDOM POLICY BASELINE
# ============================================================

print("\n" + "=" * 70)
print("RANDOM POLICY BASELINE")
print("=" * 70)

random_rewards = []
random_lengths = []

for episode in range(5):

    obs, info = env.reset(seed=200 + episode)

    total_reward = 0.0
    steps = 0

    while True:

        action = env.action_space.sample()

        obs, reward, terminated, truncated, info = env.step(
            action
        )

        total_reward += float(reward)
        steps += 1

        if terminated or truncated:
            break

    random_rewards.append(total_reward)
    random_lengths.append(steps)

print(
    f"Mean reward:       "
    f"{np.mean(random_rewards):.4f}"
)

print(
    f"Reward std:        "
    f"{np.std(random_rewards):.4f}"
)

print(
    f"Mean episode len:  "
    f"{np.mean(random_lengths):.1f}"
)

print(
    "Episode rewards:   ",
    [round(x, 4) for x in random_rewards]
)


# ------------------------------------------------------------
# Test fixed policies
# ------------------------------------------------------------

policies = {
    "No Charging (0.0)": 0.0,
    "Moderate Charging (0.5)": 0.5,
    "Maximum Charging (1.0)": 1.0
}


for name, action in policies.items():

    result = evaluate_fixed_policy(
        env,
        action_value=action,
        n_episodes=5
    )

    print(f"\n{name}")
    print("-" * 55)

    print(
        f"Mean reward:       "
        f"{result['mean_reward']:.4f}"
    )

    print(
        f"Reward std:        "
        f"{result['std_reward']:.4f}"
    )

    print(
        f"Mean episode len:  "
        f"{result['mean_length']:.1f}"
    )

    print(
        "Episode rewards:   ",
        [round(x, 4) for x in result["episode_rewards"]]
    )


    # ============================================================
# FINAL VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("COMMIT 2 VALIDATION CHECKS")
print("=" * 70)

assert env.action_space.shape == (1,)

assert env.observation_space.shape == (8,)

assert np.all(obs >= 0.0)
assert np.all(obs <= 1.0)

assert np.all(next_obs >= 0.0)
assert np.all(next_obs <= 1.0)

assert np.isfinite(reward)

assert len(random_rewards) == 5

assert all(
    length == env.max_steps
    for length in random_lengths
)

print("✓ Action space valid")
print("✓ Observation space valid")
print("✓ Observations remain within [0, 1]")
print("✓ Rewards are finite")
print("✓ Fixed policies completed successfully")
print("✓ Random policy completed successfully")
print("✓ Episode length is consistent")

print("\nCOMMIT 2 VALIDATION COMPLETE")
print("=" * 70)

