# -*- coding: utf-8 -*-
"""RL3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiBMqu-kH0b6xtXzuEu9HLpV3qbAfkUk
"""

"""
EV Charging Optimization Environment


Implementation of a custom Gymnasium environment for EV charging
optimization using the EV Charging Demand Dataset.

The environment provides:

    Observation space:
        8 normalized state variables in [0, 1]

    Action space:
        Continuous charging level in [0, 1]

The TD3 agent will be added in later commits.


"""


# IMPORTS


import numpy as np
import pandas as pd
import gymnasium as gym
from gymnasium import spaces

## DATASET CONFIGURATION


# Update this path if the dataset is stored somewhere else.
DATA_PATH = "/kaggle/input/datasets/ziya07/electric-vehicle-charging-demand-dataset/ev_charging_dataset.csv"



# LOAD DATASET


def load_dataset(path=DATA_PATH):
    """
    Load the EV charging dataset.

    Parameters
    ----------
    path : str
        Path to the CSV dataset.

    Returns
    -------
    pandas.DataFrame
        Loaded dataset.
    """

    df = pd.read_csv(path)

    # Convert timestamps to datetime objects
    time_columns = [
        "timestamp",
        "arrival_time",
        "charging_start_time",
        "charging_end_time",
    ]

    for column in time_columns:
        if column in df.columns:
            df[column] = pd.to_datetime(df[column])

    return df



# PREPARE TEMPORAL PROFILE


def prepare_profile(df):
    """
    Prepare the temporal profile used by the RL environment.

    The environment operates on the following variables:

        timestamp
        electricity_price
        station_load
        renewable_energy_ratio
        charging_demand
        hour
        date

    Parameters
    ----------
    df : pandas.DataFrame
        Raw EV charging dataset.

    Returns
    -------
    pandas.DataFrame
        Prepared temporal profile.
    """

    profile = df[
        [
            "timestamp",
            "electricity_price",
            "station_load",
            "renewable_energy_ratio",
            "charging_demand",
        ]
    ].copy()

    profile["hour"] = profile["timestamp"].dt.hour
    profile["date"] = profile["timestamp"].dt.date

    return profile.reset_index(drop=True)



# NORMALIZATION HELPER


def normalize(value, column, df):
    """
    Normalize a value to the [0, 1] range using
    the minimum and maximum values observed in the dataset.

    Parameters
    ----------
    value : float
        Value to normalize.

    column : str
        Column used to determine the normalization range.

    df : pandas.DataFrame
        Dataset containing the column.

    Returns
    -------
    float
        Normalized value in [0, 1].
    """

    min_val = df[column].min()
    max_val = df[column].max()

    if max_val == min_val:
        return 0.0

    normalized = (value - min_val) / (max_val - min_val)

    return float(np.clip(normalized, 0.0, 1.0))



# EV CHARGING ENVIRONMENT


class EVChargingEnv(gym.Env):
    """
    Custom Gymnasium environment for EV charging optimization.

    Observation vector
    ------------------
    The state contains eight normalized variables:

        0. electricity price
        1. station load
        2. renewable energy ratio
        3. charging demand
        4. hour
        5. charging demand (normalized)
        6. station load (normalized)
        7. electricity price (normalized)

    Action
    ------
    A continuous charging control value:

        0.0 -> no charging
        1.0 -> maximum charging

    Reward
    ------
    The detailed reward function will be implemented and
    validated in Commit 2.

    This commit focuses on creating and validating the
    environment structure.
    """

    metadata = {"render_modes": []}

    def __init__(self, profile, max_steps=96):
        """
        Initialize the environment.

        Parameters
        ----------
        profile : pandas.DataFrame
            Prepared temporal profile.

        max_steps : int
            Maximum number of steps per episode.
            96 steps correspond to 24 hours at 15-minute
            intervals.
        """

        super().__init__()

        self.profile = profile.reset_index(drop=True)
        self.max_steps = max_steps

        # ----------------------------------------------------
        # Action space
        # ----------------------------------------------------
        #
        # Continuous charging level:
        #
        # 0.0 = no charging
        # 1.0 = maximum charging
        #
        self.action_space = spaces.Box(
            low=np.array([0.0], dtype=np.float32),
            high=np.array([1.0], dtype=np.float32),
            dtype=np.float32,
        )

        # ----------------------------------------------------
        # Observation space
        # ----------------------------------------------------
        #
        # Eight normalized variables, each in [0, 1].
        #
        self.observation_space = spaces.Box(
            low=0.0,
            high=1.0,
            shape=(8,),
            dtype=np.float32,
        )

        self.current_step = 0
        self.start_index = 0


    # RESET

    def reset(self, seed=None, options=None):
        """
        Reset the environment.

        A random valid starting point is selected while
        maintaining enough observations for a complete episode.
        """

        super().reset(seed=seed)

        max_start = len(self.profile) - self.max_steps

        if max_start <= 0:
            self.start_index = 0
        else:
            self.start_index = int(
                self.np_random.integers(0, max_start + 1)
            )

        self.current_step = 0

        observation = self._get_observation()

        info = {
            "start_index": self.start_index,
            "timestamp": self.profile.iloc[
                self.start_index
            ]["timestamp"],
        }

        return observation, info


    # GET OBSERVATION


    def _get_observation(self):
        """
        Construct the normalized state representation.

        Returns
        -------
        numpy.ndarray
            Eight-dimensional normalized observation.
        """

        index = self.start_index + self.current_step

        row = self.profile.iloc[index]

        # ----------------------------------------------------
        # Normalize environmental variables
        # ----------------------------------------------------

        price = normalize(
            row["electricity_price"],
            "electricity_price",
            self.profile,
        )

        load = normalize(
            row["station_load"],
            "station_load",
            self.profile,
        )

        renewable = normalize(
            row["renewable_energy_ratio"],
            "renewable_energy_ratio",
            self.profile,
        )

        demand = normalize(
            row["charging_demand"],
            "charging_demand",
            self.profile,
        )

        # ----------------------------------------------------
        # Normalize hour
        # ----------------------------------------------------

        hour = float(row["hour"]) / 23.0

        # ----------------------------------------------------
        # Construct state
        # ----------------------------------------------------

        observation = np.array(
            [
                price,
                load,
                renewable,
                demand,
                hour,
                demand,
                load,
                price,
            ],
            dtype=np.float32,
        )

        return np.clip(
            observation,
            0.0,
            1.0,
        )


    #### STEP


    def step(self, action):
        """
        Execute one environment step.

        The detailed optimization reward will be introduced
        in Commit 2.

        For Commit 1, this method simply advances the
        temporal state and returns a placeholder reward.
        """

        # Ensure action is a valid NumPy array
        action = np.asarray(
            action,
            dtype=np.float32,
        )

        # Clip action to valid range
        action = np.clip(
            action,
            self.action_space.low,
            self.action_space.high,
        )

        # Placeholder reward for Commit 1
        reward = 0.0

        # Advance environment
        self.current_step += 1

        # Determine whether episode has ended
        terminated = False

        truncated = (
            self.current_step >= self.max_steps
        )

        # Get next observation if possible
        if not truncated:
            observation = self._get_observation()
        else:
            observation = np.zeros(
                self.observation_space.shape,
                dtype=np.float32,
            )

        info = {
            "action": float(action[0]),
        }

        return (
            observation,
            reward,
            terminated,
            truncated,
            info,
        )


##### SANITY TEST


def sanity_test(profile):
    """
    Perform a basic environment sanity test.

    This confirms that:

        - The environment can be created.
        - The action space is valid.
        - The observation space is valid.
        - reset() works.
        - A single environment step works.
    """

    print("=" * 70)
    print("ENVIRONMENT SANITY TEST")
    print("=" * 70)

    env = EVChargingEnv(profile)

    print("\nAction space:")
    print(env.action_space)

    print("\nObservation space:")
    print(env.observation_space)

    observation, info = env.reset(seed=42)

    print("\nInitial observation:")
    print(observation)

    print("\nInitial information:")
    print(info)

    # --------------------------------------------------------
    # Verify observation
    # --------------------------------------------------------

    assert observation.shape == (8,)
    assert np.all(observation >= 0.0)
    assert np.all(observation <= 1.0)

    # --------------------------------------------------------
    # Test one action
    # --------------------------------------------------------

    action = np.array(
        [0.5],
        dtype=np.float32,
    )

    next_observation, reward, terminated, truncated, info = env.step(
        action
    )

    print("\nAfter one step:")
    print("Action:", action)
    print("Reward:", reward)
    print("Next observation:", next_observation)
    print("Terminated:", terminated)
    print("Truncated:", truncated)
    print("Info:", info)

    print("\nSanity test passed.")



##### MAIN


if __name__ == "__main__":

    print("Loading EV charging dataset...")

    raw_df = load_dataset()

    print(
        f"Dataset loaded: {raw_df.shape}"
    )

    profile = prepare_profile(raw_df)

    print(
        f"Profile prepared: {profile.shape}"
    )

    sanity_test(profile)
```

